"""
Anupalan AI - Global State Schema
==================================
Defines the LangGraph state schema and all Pydantic models used across agents.
Every agent reads from and writes to the AnupalanState TypedDict.
"""

from typing import TypedDict, List, Optional, Annotated
from pydantic import BaseModel, Field
from typing_extensions import Literal
import operator
from datetime import datetime


# ---------------------------------------------------------------------------
# Pydantic Models
# ---------------------------------------------------------------------------

class RegulatoryEvent(BaseModel):
    """Represents a parsed regulatory circular from RBI/SEBI/FIU-IND/IRDAI."""
    circular_id: str = Field(description="Unique identifier for the circular")
    source: Literal["RBI", "SEBI", "FIU-IND", "IRDAI", "MoF"] = Field(
        description="Regulatory body that issued the circular"
    )
    doc_type: str = Field(
        description="Document type: Master Circular, Notification, Enforcement Order, Circular"
    )
    title: str = Field(default="", description="Title of the circular")
    raw_text: str = Field(description="Full extracted text of the circular")
    hash_sha256: str = Field(description="SHA-256 hash for deduplication")
    ingested_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat() + "Z",
        description="ISO timestamp of ingestion"
    )


class PolicyDelta(BaseModel):
    """Output of GraphRAG-based Legal Translation Agent."""
    intersecting_policies: List[str] = Field(
        default_factory=list,
        description="List of internal bank policies affected by this circular"
    )
    superseded_rules: List[str] = Field(
        default_factory=list,
        description="Rules/policies that are superseded by this circular"
    )
    new_requirements: List[str] = Field(
        default_factory=list,
        description="New compliance requirements extracted from the circular"
    )
    amended_requirements: List[str] = Field(
        default_factory=list,
        description="Existing requirements that have been amended"
    )
    risk_assessment: str = Field(
        default="MEDIUM",
        description="Overall risk assessment: LOW, MEDIUM, HIGH, CRITICAL"
    )
    faithfulness_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Cosine similarity score between LLM output and source context"
    )
    analysis_summary: str = Field(
        default="",
        description="LLM-generated summary of the regulatory delta"
    )


class MeasurableActionPoint(BaseModel):
    """An atomic, assignable compliance action item."""
    map_id: str = Field(description="Unique MAP identifier")
    department: str = Field(
        description="Target department: IT Security, Retail Credit, Treasury, HR, Risk, Compliance, Operations"
    )
    owner_role: str = Field(description="Role responsible for execution")
    deadline: str = Field(description="ISO date string for compliance deadline")
    risk_score: float = Field(ge=0, le=10, description="Risk score 0-10")
    priority: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(
        default="MEDIUM",
        description="Priority classification"
    )
    instructions: List[str] = Field(
        default_factory=list,
        description="Step-by-step action instructions"
    )
    evidence_requirements: List[str] = Field(
        default_factory=list,
        description="Evidence types required to validate completion"
    )
    requires_hitl: bool = Field(
        default=False,
        description="True if risk_score >= 8.0 or priority is CRITICAL"
    )
    status: Literal["PENDING", "DISPATCHED", "IN_PROGRESS", "COMPLETED", "VALIDATED", "FAILED"] = Field(
        default="PENDING",
        description="Current lifecycle status"
    )
    circular_id: str = Field(default="", description="Source circular ID")


class ComplianceEvidencePackage(BaseModel):
    """Evidence bundle generated by the Autonomous Validation Agent."""
    map_id: str = Field(description="MAP this evidence validates")
    validation_status: Literal["SUCCESS", "FAILED", "PENDING"] = Field(
        description="Result of autonomous validation"
    )
    evidence_sources: List[str] = Field(
        default_factory=list,
        description="Systems queried for evidence (SIEM, DMS, LMS, Filing Portal)"
    )
    evidence_details: List[dict] = Field(
        default_factory=list,
        description="Detailed evidence records from each source"
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat() + "Z",
        description="When validation was performed"
    )
    evidence_pdf_path: str = Field(
        default="",
        description="Path to generated evidence PDF"
    )


class RoutingLog(BaseModel):
    """Audit log for MAP routing actions."""
    map_id: str
    department: str
    ticket_id: str
    action: str
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")
    status: str = "DISPATCHED"


# ---------------------------------------------------------------------------
# LangGraph State
# ---------------------------------------------------------------------------

class AnupalanState(TypedDict):
    """
    Global state for the Anupalan AI LangGraph workflow.
    
    Flow: ingest -> graphrag_translate -> map_generate -> hitl_router ->
          [cco_review] -> route -> validate -> close
    """
    # Agent 1 output
    regulatory_event: Optional[RegulatoryEvent]
    
    # Agent 2 output
    policy_delta: Optional[PolicyDelta]
    
    # Agent 3 output
    maps: List[MeasurableActionPoint]
    
    # Agent 4 output
    routing_logs: List[dict]
    
    # Agent 5 output
    validation_evidence: List[ComplianceEvidencePackage]
    
    # HITL state
    hitl_approval: bool
    hitl_required_maps: List[str]  # map_ids requiring CCO approval
    
    # Pipeline state
    current_agent: str
    errors: List[str]
    final_status: str
    
    # Metadata
    pipeline_run_id: str
    started_at: str
    completed_at: str
